[project]
name = "chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chromadb>=1.3.5",
    "datasets>=2.19.0,<3.0.0",
    "pandas>=2.3.3",
    "sentence-transformers>=5.1.2",
    "tqdm>=4.67.1",
]
